### ISSUE TITLE
Implement according to terraform-aws-authenticating-secgroup

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/terraform-aws-iam-authenticating-group#1]
We're going to share lots of code with https://github.com/riboseinc/terraform-aws-authenticating-secgroup . Not sure if we can extract some generalized framework from it, but at least it's straightforward to do 👍

**Comment by phuonghuynh** [comment]
Good idea, 👍

**Comment by phuonghuynh** [comment]
@ronaldtse it would be great if  you have a sample usage in mind?

**Comment by ronaldtse** [comment]
Uploaded in #2

**Comment by phuonghuynh** [comment]
@ronaldtse the python API can help to do mapping user-group. So we are able to do dynamic authenticate users-groups. How about this config sample?

```json
[
    {
        "group_names": ["group1", "group2"],
        "user_names": ["user1", "user2"],
        "region_name": "us-west-1"
    },
    {
        "group_names": ["group3"],
        "user_names": ["user1"],
        "region_name": "us-west-2"
    }
]
```

**Comment by ronaldtse** [comment]
Yes this is good -- I somehow missed the users... Using Python API is good too. Thanks, let's proceed!

**Comment by ronaldtse** [comment]
@phuonghuynh any updates so far? Thanks!

**Comment by phuonghuynh** [comment]
Creating/cleaning fake policies to persist timestamp. The usage will be changed a bit. PR will be submitted soon.

We need to keep in mind that there are limitations on IAM Entities including Policies, https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_iam-limits.html

**Comment by ronaldtse** [comment]
Good to know, we're very eager to use it. Thanks!
