### ISSUE TITLE
modify the logic of which users will be added to the group

### ISSUE THREAD

**Issue by erikbor** [riboseinc/terraform-aws-iam-authenticating-group#12]
Hi @phuonghuynh,

We got the module working but we'd like to change the logic of which users will be added to the group.

We'd like **to have** the following flow:

In the module:
- we specify `user_1`, `user_2` and `user_3` to allow to authenticate
- we specify `group_dyn`1

`user_{1,2,3}` are now allowed to authenticate against the endpoint

when `user_2` authenticates, the Lambda function will add `user_2` to `group_dyn1`, no other users (e.g.: `user_1`) will not be added

when `user_3` authenticates, the Lambda function will add `user_3` to `group_dyn1`, no other users (e.g.: `user_1`) will not be added

In the **current** situation we have `user_A` that can authenticate and then `user_{1,2,3}` will be added to `group_dyn1`.

Can you please help modify the logic?

Many thanks

**Comment by phuonghuynh** [comment]
yes

**Comment by erikbor** [comment]
Hi @phuonghuynh,

We have a weird issue with two IAM users: `test1` and `test2` which are in IAM group `staff`.

If I authenticate with `test1` then `test2` gets added to the IAM group `dyn-iam-access`. It should be the other way around that `test1` gets added.

My configuration looks like this:

```
module "dyn-iam-access" {
  source         = "github.com/riboseinc/terraform-aws-iam-authenticating-group"

  providers = {
    aws = "aws"
  }

  name           = "dyn-iam-access"
  description    = "dyn-iam-access"
  time_to_expire = 300
  log_level = "DEBUG"

  iam_groups = [
    {
      "group_name" = "${aws_iam_group.dyn_iam_access.name}",
      "user_names" = [
	"test1",
	"test2"
      ]
    }
  ]
}
```

```
resource "aws_iam_policy" "dyn_iam_access" {
  name        = "dyn-iam-access-policy"
  description = "dyn-iam-access-policy"
  policy      = "${data.aws_iam_policy_document.dyn_iam_access.json}"
}

data "aws_iam_policy_document" "dyn_iam_access" {
  statement {
    effect    = "Allow"
    actions   = [
      "execute-api:Invoke"
    ]
    resources = [
      "${module.dyn-iam-access.execution_resources}"
    ]
  }
}

resource "aws_iam_group" "dyn_iam_access" {
  name = "dyn-iam-access"
  path = "/dyn-iam-access/"
}

resource "aws_iam_group_policy_attachment" "dyn_iam_access_freelancers" {
  group      = "freelance"
  policy_arn = "${aws_iam_policy.dyn_iam_access.arn}"
}

resource "aws_iam_group_policy_attachment" "dyn_iam_access_staff" {
  group      = "staff"
  policy_arn = "${aws_iam_policy.dyn_iam_access.arn}"
}
```

Can you have a look please. The enhancement is almost finished :) Thanks

**Comment by phuonghuynh** [comment]
Yes, looking this issue

**Comment by phuonghuynh** [comment]
PR submitted, @erikbor

**Comment by erikbor** [comment]
This works good now.
