### ISSUE TITLE
aws_api_gateway_stage.this: Error creating API Gateway Stage: ConflictException: Stage already exists

### ISSUE THREAD

**Issue by erikbor** [riboseinc/terraform-aws-iam-authenticating-group#24]
Hi @phuonghuynh,

I just updated a test deployment using this module.

After the update I first got something an error like `"stage_name" is empty` error, which I tried to resolve with: https://github.com/riboseinc/terraform-aws-iam-authenticating-group/pull/23/commits/b46ffcc8994c8bc44fc94e5518861debeaf26435

I added the following to define the stage in the .tf file:
```
deployment_stage = "${var.developmentstagename}-dyn-iam"
```

And now I get this error:
```
* aws_api_gateway_stage.this: Error creating API Gateway Stage: ConflictException: Stage already exists
	status code: 409, request id: 7085151a-7f6e-11e8-8186-f37fb4714d37
```

Can you please look into this? Maybe my commit needs to be reverted.

And does the example need to be updated for the `deployment_stage_name`?

Cheers

**Comment by erikbor** [comment]
After the revert of commit

I applied again and got this error:
```
Error: Error applying plan:

1 error(s) occurred:

* module.global.module.dyn-iam-access.aws_api_gateway_method_settings.this: 1 error(s) occurred:

* aws_api_gateway_method_settings.this: Updating API Gateway Stage failed: NotFoundException: Invalid stage identifier specified
	status code: 404, request id: 1e9a544c-7f72-11e8-aa6c-330b744ba238
```

**Comment by phuonghuynh** [comment]
@erikbor "destroy" then "apply" again would case this issue ? or you got this when running "update" command?

**Comment by erikbor** [comment]
@phuonghuynh I think this is related to a race condition.

Before I apply I delete all the existing Lambda and endpoint stuff, and then `terraform apply`. When Terraform fails and I run `terraform apply` again then there are no problems.

So let's leave it to that for now.

Thanks for checking.
