### ISSUE TITLE
Rename the object key in S3 to have the .json file extension

### ISSUE THREAD

**Issue by erikbor** [riboseinc/terraform-aws-iam-authenticating-group#33]
@phuonghuynh 

Can you please update the module so it uses the .json file extension?

Thanks!

**Comment by phuonghuynh** [comment]
@erikbor the module should check all objects to rename them if they not are in ".json" ext ?

**Comment by ronaldtse** [comment]
We don’t need it to check, but we just want to ensure that the files have the “.json” extension. The lambda function should just assume there is “.json” extension.
