### ISSUE TITLE
Can you also fix the `forces new resource` bug in this module

### ISSUE THREAD

**Issue by erikbor** [riboseinc/terraform-aws-iam-authenticating-group#7]
Hi @phuonghuynh,

We also get the constant `forces new resource` bug in this module:

`-/+ module.testenv.module.dynamic-iam-group.module.lamda_authorize.aws_lambda_function.this (new resource required)
      id:                  "authorize-iam-group-77fc237da3b1" => <computed> (forces new resource)
`

Can you help fix this one too please?

Thanks!!!

**Comment by phuonghuynh** [comment]
yes

**Comment by erikbor** [comment]
This is done, thanks.
