### ISSUE TITLE
Publish in Terraform Registry

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/terraform-aws-iam-authenticating-group#8]
Hi @phuonghuynh , could you also help publish this in the Terraform Registry? Thanks!

**Comment by phuonghuynh** [comment]
I getting 503 error many times, so i think i am unable to publish this module. @erikbor / @ronaldtse  could you help with this?

<img width="1078" alt="screenshot at may 01 11-03-12" src="https://user-images.githubusercontent.com/705510/39460666-78796fe2-4d2f-11e8-909d-633e74a6ee06.png">

**Comment by ronaldtse** [comment]
Actually that’s the reason I asked you :wink 

I wonder when it will be fixed?

**Comment by ronaldtse** [comment]
Maybe you can post a ticket to them?

**Comment by phuonghuynh** [comment]
Yes, i posted new ticket to them; they are checking it, https://github.com/hashicorp/terraform/issues/17979

**Comment by phuonghuynh** [comment]
@ronaldtse just want to to let you know a fix coming ^

**Comment by ronaldtse** [comment]
@phuonghuynh eager to see it 👍

**Comment by phuonghuynh** [comment]
@ronaldtse i think you can publish it now ^ (i am unable to do that since i am not the admin)

<img width="745" alt="screenshot at may 08 23-12-59" src="https://user-images.githubusercontent.com/705510/39769141-8c99cddc-5315-11e8-9edf-b0fe95be4fce.png">

**Comment by ronaldtse** [comment]
Published! https://registry.terraform.io/modules/riboseinc/iam-authenticating-group/aws/1.0.0
